### ISSUE TITLE
update to 19.21

### ISSUE THREAD

**Issue by weirros** [JpnTr/Jetson-Nano-Install-Dlib-Library#1]
replace dlib-19.18.tar.bz2 to dlib-19.21.tar.bz2
and if python36

and you forgot CUDA;

cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1

then 

sudo python3 setup.py install
@20200923

**Comment by JpnTr** [comment]
thank u for issue
